apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: tap-demo
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: tap-demo
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  - name: gitops_ssh_secret
    value: git-ssh
  - name: gitops_repository
    value: ssh://git@github.com/dbha/tap-demo-config.git
  - name: gitops_branch
    value: main
  - name: gitops_commit_message
    value: bump  
  source:
    git:
      url: https://github.com/dbha/tap-demo
      ref:
        branch: main
